#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          ts3 server
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Teamspeak 3 server
# Description:       Daemon for TS3 server
### END INIT INFO

USER=ts3-user
DESC="Teamspeak 3 server"
DAEMON=/opt/ts3-server/ts3server_startscript.sh

sudo -u $USER $DAEMON $1 $OPTIONS
